language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: c85wDAqQGImp9lRrKg+sD2I2dyxkVulV/MazjqLvJBuBRMEGP1/lMsNCj8WJadbMMTVOMuwrET2ilmoUPtH2Pk9NASKyMOAa0afgYwfEDk0pHdb4vDbtYQsUzSybkpikyl5lBZV5V1fERilyr4Wg2JNYwcVmWGKOTtSyhI9miWpOhC2htajz0zx+HdqLBiFCQ8yd+TNXjPQz8aWqFMw0/3j5LC3DnIlPS9/71qOrJodg8JcyjJR9f/UTLVxRHKkD/DdtIl04Qmm5bQ4n7+M6V1lKiG1LFE7XJZdb2LRvBdu35Eyu4LQjLrZpIa8mrp9JwpShB/XMtGByiCUjfDaX7iM3eR3Wyx9Xf6KIZSRQfc71ej4aTTJtRSYwXn9YA+EQRmFlclLbhWU+UxZRG4OEZm+oO98w8yBAVnfyfpuXEcjbDeC2znndR6yjw/DCFD6GFs7jbWIGU9PDJk8daHFsnC6B5ifN/LpH/vJMV1SUjvCVGrTip6qWgkPjq6tkVe8ekyVPDOgkGZU01truoBrfWPujULRtm7X/26kUs4xRzFi4n+SL9MzmdRFNOOtEgM+MMOzSsHkvGkEaUWqaS4ICnb/U88zQWw23JLkcGk0m0Y2n6ajJ1daFA/dcwXWDRl1JlD1sXu3FteGFuj+nFoG4nqp0sukOta1WmpjKXDEf7pM=
  on:
    tags: true
    repo: jcreinhold/tiramisu_brulee
    python: 3.8
